### ISSUE TITLE
能否请教一下，仍然是default-config.json问题

### ISSUE THREAD

**Issue by deardeerluluu** [GlassyWing/bi-lstm-crf#10]
我使用您文末分享的两个_dic.json和default-config.json搭配使用是可以正常训练的，但是加入预训练字向量的路径后出现和之前几位仁兄一样的报错：

KeyError: 'max_num_words'
Traceback (most recent call last):
  File "train_example_emb.py", line 55, in <module>
    save_config(segmenter, config_save_path)
  File "/home/ziyao/projects/bi-lstm-crf/dl_segmenter/__init__.py", line 9, in save_config
    json.dump(obj.get_config(), file)
AttributeError: 'NoneType' object has no attribute 'get_config'

能否请教一下？

**Comment by longlong520** [comment]
解决了吗？我也遇到了同样的问题。

**Comment by deardeerluluu** [comment]
> 解决了吗？我也遇到了同样的问题。
没有
